### ISSUE TITLE
metrics.py: cannot import name ZabbixMetric

### ISSUE THREAD

**Issue by ekoort** [ria-ee/X-Road-scripts#1]
> #cat /etc/debian_version
8.7
 #apt-get install python-pip
 #pip install pyzabbix
 #pip install py-zabbix
 #./metrics.py --env -c metrics.cfg
Traceback (most recent call last):
  File "./metrics.py", line 8, in <module>
    from pyzabbix import ZabbixMetric, ZabbixSender, ZabbixAPI
ImportError: cannot import name ZabbixMetric

What's missing?

**Comment by VitaliStupin** [comment]
Not sure what happens if you install both pyzabbix and py-zabbix. Maybe they conflict in some way. The correct module is py-zabbix and in my test machine its version is 1.1.3.

Also I am using Ubuntu 14.04, but that probably should not influence the "pip".

**Comment by ekoort** [comment]
Uninstalling and clearing all related to pyzabbix did the trick.
