### ISSUE TITLE
metrics.py - annab imalikke vigu

### ISSUE THREAD

**Issue by lauri-aloauri** [ria-ee/X-Road-scripts#3]
Tere ! me püüma x-tee v6 arenduskeskkonna turvaserveri osas rakendada nn 2Health and Environment monitoring" zabbix montooringut kasutades oma zabbix serverit kuid me saame imalikke vigu metrics.py  poolt.

Thread-5: Adding Application: 'ee-dev/GOV/70000740/ehis/tallhaOppimineList/v1' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[successfulRequestCount]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[unsuccessfulRequestCount]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[requestMinDuration]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[requestAverageDuration]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[requestMaxDuration]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[requestDurationStdDev]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[requestMinSoapSize]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[requestAverageSoapSize]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[requestMaxSoapSize]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[requestSoapSizeStdDev]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[responseMinSoapSize]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[responseAverageSoapSize]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[responseMaxSoapSize]' for host_id '10215'.
Thread-5: Adding item: 'ee-dev.GOV.70000740.ehis.tallhaOppimineList.v1[responseSoapSizeStdDev]' for host_id '10215'.
Thread-5: Adding Application: 'ee-dev/GOV/70000740/ehis/tallhaOppimineList/V1' for host_id '10215'.
Thread-5: ERROR: 'Cannot add Application 'ee-dev/GOV/70000740/ehis/tallhaOppimineList/V1' to Host 'ee-dev.COM.10264823.turvameesv6-arendus.213.184.55.180'!'

Imelik on see kust ta leiab tallhaOppimineList/V1 teenuse kus see v sümbol on suure tähega, sa
mas turvaserveris on ainult üks teenus.  Sama meil tekib zabbix appication alla tekib see teenus väikese tähega ee-dev/GOV/70000740/ehis/tallhaOppimineList/v1 , kuid see skript leiab ei te kust veel ühe ja see kord suure tähega ja satub hämmingusse andes vea. Peale viga enam uusi teenuseid zabbix application alla ei teki ja skript lõpetab oma tegevuse. 

Huvitav kus see probleem võiks paikneda skptis või on see mingi wsdl teema !?!

**Comment by VitaliStupin** [comment]
Teenuste nimetused tulevad otse turvaserverist, mitte WSDL'idest. Kui keegi kutsus väja teenuse mida pole olemas või vale versiooniga, siis see kajastub ka teenuste monitooringus täpselt samal kujul nagu seda kutsuti välja.

Tundub, et probleem tekkib sellest, et mõnikord tallhaOppimineList teenust kutsutakse vale versiooniga "V1" (suur "V" täht). Ja Zabbix arvatavasti keeldub lisama uue "Application'i" mille kood on juba lisatud väikse versiooni tähega.

Ma uurin kas see probleem on tingitud uuema Zabbix'i versiooni kasutamisega, kuna "Zabbix 3.0 LTS" puhul ma ei suutnud seda probleemi reprodutseerida.

**Comment by VitaliStupin** [comment]
Probleem on tingitud vale collation'i kasutamisega Zabbixi MySQL andmebaasis. Probleemi parandamiseks tuleks kasutada õige collation'i:
```mysql
create database zabbix character set utf8 collate utf8_bin;
```
