### ISSUE TITLE
Missing header errors from Zabbix when running metrics.py

### ISSUE THREAD

**Issue by bthj** [ria-ee/X-Road-scripts#6]
Hi

When trying out the `metrics.py` (X-Road Health and Environment monitoring collector for Zabbix) script against Zabbix `1:4.0.30-1+bionic`, with a command like
```
python3 metrics.py -c metrics.cfg
```
I get the error:  `Cannot connect to Zabbix`

In `/var/log/zabbix/zabbix_server.log` there is printed the error:
```
Message from 127.0.0.1 is missing header. Message ignored.
```

In version 4 of Zabbix, there seems to have been introduced the requirement of [sending a header](https://www.zabbix.com/documentation/4.0/manual/appendix/protocols/header_datalen).

Could the issue be that `py-zabbix` is not able to send that required header?  - haven't been able to find anything on that in the `py-zabbix` project.

Is anyone successfully using this script with Zabbix 4 ?

**Comment by VitaliStupin** [comment]
Hi!

I have just tried metrics.py with Zabbix version 4.0.30 and py-zabbix 1.1.7 and it worked just fine. Maybe you have some newer Zabbix or older py-zabbix installed?

Also you can try debug mode by changing metrics.cfg to:
```
[metrics]
debug = 3
```

**Comment by bthj** [comment]
I'm using exactly those versions.

In `metrics.cfg` I have:  `zabbix_url = http://127.0.0.1:10051`.

Must be some misconfiguration on my part - am not an experienced Zabbix user and just wanted to quickly fire it up to see how the data is presented there.

**Comment by bthj** [comment]
With `debug = 3` the output is:
```
$ python3 metrics.py -c metrics.cfg
MainThread: Configuration loaded from 'metrics.cfg'.
MainThread: Collecting Health Monitoring.
MainThread: ERROR: 'Cannot connect to Zabbix.
URL: http://127.0.0.1:10051
Detail: Remote end closed connection without response'
```
and as before, in `/var/log/zabbix/zabbix_server.log`:
```
  4666:20210413:095443.468 Message from 127.0.0.1 is missing header. Message ignored.
```

**Comment by VitaliStupin** [comment]
You are using incorrect port. You need to configure Zabbix API port, which is the same as UI port (80/443).

Fastest way to test Zabbix 4.0 would be to use official docker-compose script:
https://github.com/zabbix/zabbix-docker/blob/4.0/docker-compose_v3_ubuntu_mysql_local.yaml

**Comment by bthj** [comment]
The dashboard is accessible at:  http://localhost/zabbix/zabbix.php?action=dashboard.view
But if I set `zabbix_url = http://localhost/` then the script returns:
```
Detail: HTTP Error 404: Not Found'
```

**Comment by bthj** [comment]
Thanks for the link to the Docker Compose declaration, that works much better, even though it sets up Zabbix 5.2

Now I've imported the [envmon_template.xml](https://github.com/ria-ee/X-Road-scripts/blob/master/zabbix/envmon_template.xml) and was able to run the script and see some data being populated in the Zabbix UI.


May I ask how you are utilizing this?

I'm unfamiliar with Zabbix but when I navigate to `Monitoring->Latest Data` and `Monitoring->Hosts` I see some entries.

Are you creating custom reports for this?

Do you have alerting set up?  If so, what values / conditions do you use to trigger alerts?

**Comment by VitaliStupin** [comment]
You have Zabbix 5.2 because you did not check out 4.0 branch, but I am glad to hear that script works with 5.2 as well.

I do know that "Latest Data" is used for business decisions. For example it is possible for X-Road Centre to see the distribution of versions of Security Servers installed in a particular X-Road instance. Also it can be useful while supporting X-Road members (Low disk space? Low memory? Unsupported version?). But unfortunately I do not have information about setting up alerting and reporting.

**Comment by bthj** [comment]
Thanks for the help and information :)
